Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

#from cart.views import cartHome
from .views import home_page
from userApp.views import user_logout
urlpatterns = [
    # url(r'^$', include('homeApp.urls')),
    #path('cart/',cartHome,name='cart'),
    url(r'^$', home_page,name='home'),
    path('admin/', admin.site.urls),
    url(r'cart/',include('cart.urls',namespace='cart')),
    url(r'category/',include('categoryApp.urls',namespace='category')),
    url(r'^userApp/',include('userApp.urls')),
    url(r'^order/',include('order.urls')),
    url(r'^logout/$',user_logout, name='logout'),
    url(r'^seller/',include('seller.urls')),
    url(r'^search/', include("search.urls", namespace='search')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url

from .views import cartHome,cartUpdate

app_name='cart'
urlpatterns=[
    url(r'^$',cartHome,name='cartHome'),
    url(r'^update/$',cartUpdate,name='cartUpdate'),
]

order/urls.py
from django.conf.urls import url
from .views import createOrder,setAddress,orderHistory
app_name='order'

urlpatterns=[
    url(r'^create_order/$',createOrder,name='createOrder'),
    url(r'^deliver_to/$',setAddress,name='setAddress'),
    url(r'^order_history$',orderHistory,name='orderHistory'),
]

order/models.py
from django.db import models
from cart.models import Cart
from categoryApp.utils import unique_order_id_generator
from django.db.models.signals import pre_save,post_save
from django.contrib.auth.models import User
# Create your models here.
ORDER_STATUS_CHOICES = (
    ('created', 'Created'),
    ('paid', 'Paid'),
    ('shipped', 'Shipped'),
)
class Order(models.Model):
    order_id = models.CharField(max_length=120,blank=True)
    cart = models.OneToOneField(Cart,on_delete=models.CASCADE,null=True,blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    active = models.BooleanField(default=True)
    total = models.DecimalField(default=0.00,max_digits=100,decimal_places=2)
    address = models.CharField(max_length=120,blank=True)

    def __str__(self):
        return self.order_id

    def update_total(self):
        cart_total=self.cart.total
        self.total=cart_total
        self.save()
        return cart_total

def pre_save_create_order_id(sender,instance,*args,**kwargs):
    if not instance.order_id:
        instance.order_id = unique_order_id_generator(instance)

pre_save.connect(pre_save_create_order_id,sender=Order)

def post_save_order(sender,instance,created,*args,**kwargs):
    if created:
        instance.total=instance.update_total()
        instance.save()
        #print("ch")
        print(instance.total)

post_save.connect(post_save_order,sender=Order)

def post_save_cart_total(sender,instance,created,*args,**kwargs):
    if not created:
        #print("f")
        print(instance.id)
        qs=Order.objects.filter(cart__id=instance.id)
        if qs.count()==1:
            qs.first().update_total()
            qs.first().save()

post_save.connect(post_save_cart_total,sender=Cart)

order/forms.py
from django import forms

from .models import Order

class AddressForm(forms.ModelForm):
    class Meta:
        model = Order
        fields=[
            'address',
        ]

order/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect,HttpResponse
from .models import Order
from cart.models import Cart
from seller.models import Medium
from userApp.models import UserProfileInfo
from django.db import transaction,IntegrityError

#https://docs.djangoproject.com/en/2.0/topics/db/transactions/
#https://stackoverflow.com/questions/31734306/django-transactions-atomic-requests?rq=1
# Create your views here.
@transaction.non_atomic_requests
def createOrder(request):
    if request.user.is_authenticated:
        cart_obj=Cart.objects.filter(user=request.user,active=True,total__gte=0.01).first()
        #print(cart_obj)
        if cart_obj is not None:
            order_obj=Order.objects.filter(cart=cart_obj).first()
            #print("hehehe")
            #print(order_obj)
            user_info=UserProfileInfo.objects.filter(user=request.user).first()
            print(user_info)
            if order_obj is None:
                Order.objects.create(cart=cart_obj)
                order_obj=Order.objects.filter(cart=cart_obj).first()
                order_obj.user=request.user
                order_obj.save()
            return render(request,"order/checkout.html",{'cart_obj':cart_obj,'order_obj':order_obj,'user_info':user_info,'isSeller':request.session['isSeller']})
        else:
            return HttpResponse("This cart is inactive, go back and click on Cart icon to active new Cart")
    else:
        return render(request, 'userApp/login.html', {'redirect_url':request.build_absolute_uri})

#must run under a transatcion

def setAddress(request):
    if request.method=="POST":
        try:
            address=request.POST.get('address')
            #print("papa")
            order_id=request.POST.get('order_id')
            print(order_id)
            cart_id=request.POST.get('cart_id')
            cart_obj=Cart.objects.get(id=cart_id)
            print(cart_obj.active)
            if cart_obj.active:
                order_obj=Order.objects.filter(order_id=order_id).first()

                for item in cart_obj.products.all():
                    print(item.price)
                    medium_obj=Medium.objects.filter(product_id=item.id,quantity__gte=1).first()

                    if medium_obj:
                        medium_obj.quantity=medium_obj.quantity-1
                        medium_obj.save()
                        print(medium_obj.quantity)
                    else:
                        return HttpResponse("At least one of your Item in cart is Out Of Stock and has been removed from it! ")
                order_obj.address=address
                order_obj.active=False
                print(request.POST.get('updateAddress'))
                order_obj.save()
                cart_obj.active=False
                cart_obj.save()
                if request.POST.get('updateAddress') is not None:
                    user_obj=UserProfileInfo.objects.filter(user=request.user).first()
                    user_obj.address=order_obj.address
                #    print(user_obj.user.username)
                    print("go")
                    user_obj.save()
                return render(request,'order/payment.html',{'isSeller':request.session['isSeller']})
            else:
                return HttpResponse("Order already has been Placed. You can't place same order multiple time.")
        except IntegrityError:
            handle_exception()
            return HttpResponse("Your all active order has been Placed!")
    return HttpResponse("Create order first to set address")

@transaction.non_atomic_requests
def orderHistory(request):
    if request.user.is_authenticated:
        order=Order.objects.filter(user=request.user,active=False)
        return render(request,'order/order_history.html',{'order':order})

    return redirect('home')

order/templates/order/checkout.html
{% extends "home/base.html" %}
<link href="https://fonts.googleapis.com/css?family=Cormorant+Garamond" rel="stylesheet">
{% block style_block %}
<style media="screen">
h1,h2{
font-family: 'Cormorant Garamond', serif;
}
</style>
{% endblock %}
{% block body_block %}
<div class="container">
<h1 class="text-center">Enter address where you want to get delivery of your order</h1>
<h2> Order ID: {{order_obj}}</h2>
<h2>Cart ID: {{cart_obj}}</h2>
<h2>Username: {{cart_obj.user.username}}</h2>
<h2>Current Delivery Address: {{order_obj.address}}</h2>
<form class="form-horizontal" action="{% url 'order:setAddress' %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="order_id" value="{{order_obj}}"/>
  <input type="hidden" name="cart_id" value="{{cart_obj}}"/>
  <div class="form-group">
    <label class="control-label col-sm-3" style="text-align: left;" for="address">Update Delivery Address:</label>
    <div class="col-sm-12">
      <input type="text" style="text-align: left;" class="form-control" name="address" placeholder="Enter Delivery Address">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <div class="checkbox">
        <label><input name="updateAddress" type="checkbox"> Update Profile Address </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-success">Submit</button>
    </div>
  </div>
</form>
</div>
{% endblock %}

order/templates/order/order_history.html
{% extends "home/base.html" %}
{% block style_block %}
{% endblock %}
{% block body_block %}

<h1 class="text-center">Order History</h1>
{% if order %}
<table class="table table-bordered">
   <thead>
     <tr>
       <th>Order ID</th>
       <th>Delivery Address</th>
       <th>Order Cost</th>
     </tr>
   </thead>
   <tbody>
     {% for item in order %}
     <tr>
       <th scope="row">{{ item.order_id }}</th>
       <td>{{ item.address }}</td>
       <td> Rs: {{ item.total }}</td>
     </tr>
     {% endfor %}
   </tbody>
 </table>
 {% else %}
 <p class="lead">Order list is empty!</p>
{% endif %}
{% endblock %}

order/templates/order/payment.html
{% extends "home/base.html" %}
{% block body_block %}
<div class="container">
<h1>Your Order has been received! It will be delivered in 3-4 days.</h1>
</div>

{% endblock %}